import email
import re
from pathlib import Path
from typing import Dict, List, Optional

ROOT_DIR = Path(__file__).resolve().parent.parent

SITE_PACKAGES_DIRS = [
    ROOT_DIR / "venv" / "lib" / "python3.11" / "site-packages",
    ROOT_DIR / "venv" / "lib" / "python3.12" / "site-packages",
    ROOT_DIR / "venv-cuda" / "lib" / "python3.11" / "site-packages",
    ROOT_DIR / "venv-cuda" / "lib" / "python3.12" / "site-packages",
]

PREAMBLE_TEXT = """# Acknowledgements

Blombooru is open source software licensed under the [MIT License](https://github.com/mrblomblo/blombooru/blob/main/LICENSE.txt).

Blombooru does not package or ship third-party dependencies directly, with the sole exception of Chart.js which is bundled as a static vendor asset. All other dependencies are installed independently by the user via Python requirements files (`requirements.txt`, `requirements-cuda.txt`) or external tooling (such as the standalone Tailwind CSS CLI).

The following is a list of third-party software dependencies utilized by Blombooru, along with their respective licenses and notices.  
This list is automatically generated by the `generate_acknowledgements.py` script."""

# Assets that are NOT installed via pip, and therefore have no dist-info
VENDORED_DEPENDENCIES: List[Dict[str, str]] = [
    {
        "Name": "tailwindcss",
        "Version": "4.2.1",
        "License": "MIT",
        "Author": "Adam Wathan, Jonathan Reinink, David Hemphill, Robin Malfait",
        "License Path": "tailwind/Tailwind.LICENSE.txt",
    },
    {
        "Name": "chart.js",
        "Version": "4.5.1",
        "License": "MIT",
        "Author": "Nick Downie, Chart.js Team and contributors",
        "License Path": "frontend/static/js/vendor/chart.js.LICENSE.txt",
    },
]

_FALLBACK_MIT_NOTICE = """MIT License

Copyright (c) {holder}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

_REQ_LINE_RE = re.compile(
    r"""^
    (?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)
    \s*(?:\[[^\]]*\])?
    \s*(?P<op>==|>=|<=|~=|!=|>|<)?
    \s*(?P<version>[^;#\s]*)
    """,
    re.VERBOSE,
)

def find_requirements_packages() -> Dict[str, str]:
    packages: Dict[str, str] = {}
    for req_file in sorted(ROOT_DIR.glob("requirements*.txt")):
        for raw_line in req_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.split("#", 1)[0].strip()
            if not line or line.startswith("-"):
                continue

            match = _REQ_LINE_RE.match(line)
            if not match:
                continue

            name = match.group("name").strip()
            version = (match.group("version") or "").strip()
            op = match.group("op")

            if name not in packages or (op == "==" and not packages[name]):
                packages[name] = version
    return packages

def find_dist_info(pkg_name: str) -> Optional[Path]:
    norm = pkg_name.lower().replace("-", "_")
    for sdir in SITE_PACKAGES_DIRS:
        if not sdir.exists():
            continue
        for p in sdir.glob("*.dist-info"):
            name_part = p.name.split("-")[0].lower().replace("-", "_")
            if name_part == norm:
                return p
    return None

def decode_header_value(val: str) -> str:
    if not val:
        return ""
    if "=?" in val and "?=" in val:
        try:
            from email.header import decode_header
            parts = decode_header(val)
            decoded = []
            for content, encoding in parts:
                if isinstance(content, bytes):
                    decoded.append(content.decode(encoding or "utf-8", errors="replace"))
                else:
                    decoded.append(str(content))
            return "".join(decoded)
        except Exception:
            return str(val)
    return str(val)

def clean_author(raw: str) -> str:
    if not raw:
        return ""
    decoded = decode_header_value(str(raw))
    decoded = " ".join(decoded.split())

    if "<" in decoded and ">" in decoded:
        # Check for quoted list of multiple authors
        quoted_match = re.findall(r'"([^"]+)"\s*<[^>]+>', decoded)
        if quoted_match and len(quoted_match) == 1 and "," in quoted_match[0]:
            return quoted_match[0].strip()

        parts = []
        for segment in re.split(r",\s*(?=[^<]*<)", decoded):
            m = re.match(r'^"?([^"]+?)"?\s*<[^>]+>$', segment.strip())
            if m:
                name = m.group(1).strip()
                if name:
                    parts.append(name)
            else:
                s = re.sub(r"<[^>]+>", "", segment).strip()
                if s:
                    parts.append(s.strip("\"'"))
        if parts:
            return ", ".join(parts)

    cleaned = decoded.strip("\"'")
    if cleaned == "protobuf@googlegroups.com":
        return "Protocol Buffers authors"
    return cleaned

def get_license_text(pkg_name: str, dist_path: Optional[Path]) -> str:
    """Read the real license text shipped by the installed package itself."""

    if pkg_name.lower().startswith("nvidia-"):
        for sdir in SITE_PACKAGES_DIRS:
            if not sdir.exists():
                continue
            for nv_dist in sdir.glob("nvidia_*.dist-info"):
                for lf in nv_dist.glob("licenses/*"):
                    if lf.is_file():
                        try:
                            return lf.read_text(encoding="utf-8", errors="replace").strip()
                        except Exception:
                            pass

    if dist_path:
        lic_files: List[Path] = []
        lic_files.extend(dist_path.glob("LICENSE*"))
        lic_files.extend(dist_path.glob("COPYING*"))
        lic_files.extend(dist_path.glob("licenses/*"))
        lic_files.extend(dist_path.glob("licenses/**/*"))
        lic_files = [f for f in lic_files if f.is_file()]

        if lic_files:
            texts = []
            seen = set()
            for lf in lic_files:
                try:
                    txt = lf.read_text(encoding="utf-8", errors="replace").strip()
                    if txt and txt not in seen:
                        seen.add(txt)
                        texts.append(txt)
                except Exception:
                    pass
            if texts:
                return "\n\n========================================\n\n".join(texts)

    return "No license text found."

def extract_package_info(pkg_name: str, version: str) -> Dict[str, str]:
    dist_path = find_dist_info(pkg_name)
    author = ""
    license_name = ""

    if dist_path:
        meta_file = dist_path / "METADATA"
        if meta_file.exists():
            try:
                text = meta_file.read_text(encoding="utf-8", errors="replace")
                msg = email.message_from_string(text)
                raw_author = (
                    msg.get("Author") or
                    msg.get("Author-email") or
                    msg.get("Maintainer") or
                    msg.get("Maintainer-email") or
                    ""
                )
                author = clean_author(str(raw_author))

                # PEP 639 License-Expression takes priority over the legacy
                # free-text License field when present.
                raw_license = msg.get("License-Expression") or msg.get("License") or ""
                license_name = decode_header_value(str(raw_license)).strip()

                if not license_name or "\n" in license_name:
                    classifiers = msg.get_all("Classifier") or []
                    for c in classifiers:
                        if c.startswith("License :: OSI Approved :: "):
                            license_name = c.replace("License :: OSI Approved :: ", "").strip()
                            break
                        elif c.startswith("License :: "):
                            license_name = c.replace("License :: ", "").strip()
                            break

                if not version:
                    version = str(msg.get("Version", ""))
            except Exception:
                pass

    if not author and pkg_name.lower().startswith("nvidia-"):
        author = "Nvidia CUDA Installer Team"

    if (not license_name or "\n" in license_name) and pkg_name.lower().startswith("nvidia-"):
        license_name = "NVIDIA Software License Agreement"

    if not license_name:
        license_name = "Unknown"

    license_text = get_license_text(pkg_name, dist_path)

    if author:
        author = " ".join(str(author).split())

    return {
        "Name": pkg_name,
        "Version": version,
        "License": license_name.strip(),
        "Author": author,
        "License Text": license_text.strip(),
    }

def load_vendored_dependencies() -> List[Dict[str, str]]:
    entries = []
    for dep in VENDORED_DEPENDENCIES:
        license_text = None
        rel_path = dep.get("License Path") or dep.get("License File")
        if rel_path:
            candidate = ROOT_DIR / rel_path
            if candidate.exists():
                try:
                    license_text = candidate.read_text(encoding="utf-8").strip()
                except Exception:
                    license_text = None

        if not license_text:
            license_text = _FALLBACK_MIT_NOTICE.format(holder=f"{dep['Name']} contributors")

        entries.append({
            "Name": dep["Name"],
            "Version": dep["Version"],
            "License": dep["License"],
            "Author": dep["Author"],
            "License Text": license_text,
        })
    return entries

def format_entry(info: Dict[str, str]) -> str:
    lines = [
        f"Name: {info['Name']}",
        f"Version: {info['Version']}",
        f"License: {info['License']}",
        f"Author: {info['Author']}",
        "License Text:",
        "===",
        "",
        info["License Text"],
    ]
    return "\n".join(lines)

def generate_acknowledgement_entries() -> List[Dict[str, str]]:
    packages = find_requirements_packages()
    entries: List[Dict[str, str]] = []

    for pkg_name, version in sorted(packages.items(), key=lambda x: x[0].lower()):
        entries.append(extract_package_info(pkg_name, version))

    for extra in load_vendored_dependencies():
        if not any(e["Name"].lower() == extra["Name"].lower() for e in entries):
            entries.append(extra)

    entries.sort(key=lambda x: x["Name"].lower())
    return entries

def generate_markdown(entries: List[Dict[str, str]]) -> str:
    formatted_entries = [format_entry(e) for e in entries]
    body = "\n\n---\n\n".join(formatted_entries)
    return PREAMBLE_TEXT + "\n\n---\n\n" + body + "\n"

def main() -> None:
    entries = generate_acknowledgement_entries()

    md_path = ROOT_DIR / "ACKNOWLEDGEMENTS.md"
    md_path.write_text(generate_markdown(entries), encoding="utf-8")

    # Ensure no stale JSON file remains
    json_path = ROOT_DIR / "ACKNOWLEDGEMENTS.json"
    if json_path.exists():
        json_path.unlink()

    print(f"Successfully generated {md_path} with {len(entries)} dependencies.")

if __name__ == "__main__":
    main()
